// Export all components for easier imports
export { default as HeroWithNavigation } from './HeroWithNavigation'
export { default as LogoSection } from './LogoSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as PricingSection } from './PricingSection'
export { default as CTASection } from './CTASection'
export { default as ProcessSection } from './ProcessSection'
export { default as ProductShowcaseSection } from './ProductShowcaseSection'
export { default as ExampleScenariosSection } from './ExampleScenariosSection'
export { default as IndustryShowcaseSection } from './IndustryShowcaseSection'
export { default as Footer } from './Footer'
